/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actions</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see robot.dSL.DSLPackage#getActions()
 * @model
 * @generated
 */
public interface Actions extends EObject
{
} // Actions
