/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.ColorLiteral#getColor <em>Color</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getColorLiteral()
 * @model
 * @generated
 */
public interface ColorLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link robot.dSL.ColorEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see robot.dSL.ColorEnum
   * @see #setColor(ColorEnum)
   * @see robot.dSL.DSLPackage#getColorLiteral_Color()
   * @model
   * @generated
   */
  ColorEnum getColor();

  /**
   * Sets the value of the '{@link robot.dSL.ColorLiteral#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see robot.dSL.ColorEnum
   * @see #getColor()
   * @generated
   */
  void setColor(ColorEnum value);

} // ColorLiteral
