/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see robot.dSL.DSLFactory
 * @model kind="package"
 * @generated
 */
public interface DSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.DSL.robot";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DSLPackage eINSTANCE = robot.dSL.impl.DSLPackageImpl.init();

  /**
   * The meta object id for the '{@link robot.dSL.impl.MarsRoverExpeditionImpl <em>Mars Rover Expedition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.MarsRoverExpeditionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getMarsRoverExpedition()
   * @generated
   */
  int MARS_ROVER_EXPEDITION = 0;

  /**
   * The feature id for the '<em><b>Missionlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARS_ROVER_EXPEDITION__MISSIONLIST = 0;

  /**
   * The number of structural features of the '<em>Mars Rover Expedition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARS_ROVER_EXPEDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.MissionImpl <em>Mission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.MissionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getMission()
   * @generated
   */
  int MISSION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Behaviorlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__BEHAVIORLIST = 1;

  /**
   * The number of structural features of the '<em>Mission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link robot.dSL.impl.BehaviorImpl <em>Behavior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.BehaviorImpl
   * @see robot.dSL.impl.DSLPackageImpl#getBehavior()
   * @generated
   */
  int BEHAVIOR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Sensor Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__SENSOR_EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Actionlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR__ACTIONLIST = 2;

  /**
   * The number of structural features of the '<em>Behavior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ExpressionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 3;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ActionsImpl <em>Actions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ActionsImpl
   * @see robot.dSL.impl.DSLPackageImpl#getActions()
   * @generated
   */
  int ACTIONS = 4;

  /**
   * The number of structural features of the '<em>Actions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link robot.dSL.impl.LeftMovementActionImpl <em>Left Movement Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.LeftMovementActionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getLeftMovementAction()
   * @generated
   */
  int LEFT_MOVEMENT_ACTION = 5;

  /**
   * The feature id for the '<em><b>Leftmove</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_MOVEMENT_ACTION__LEFTMOVE = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Left Movement Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_MOVEMENT_ACTION_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.RightMovementActionImpl <em>Right Movement Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.RightMovementActionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getRightMovementAction()
   * @generated
   */
  int RIGHT_MOVEMENT_ACTION = 6;

  /**
   * The feature id for the '<em><b>Rightmove</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_MOVEMENT_ACTION__RIGHTMOVE = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Right Movement Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_MOVEMENT_ACTION_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.RotateMovementActionImpl <em>Rotate Movement Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.RotateMovementActionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getRotateMovementAction()
   * @generated
   */
  int ROTATE_MOVEMENT_ACTION = 7;

  /**
   * The number of structural features of the '<em>Rotate Movement Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_MOVEMENT_ACTION_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link robot.dSL.impl.RotatePointsImpl <em>Rotate Points</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.RotatePointsImpl
   * @see robot.dSL.impl.DSLPackageImpl#getRotatePoints()
   * @generated
   */
  int ROTATE_POINTS = 8;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_POINTS__DEGREES = ROTATE_MOVEMENT_ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rotate Points</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_POINTS_FEATURE_COUNT = ROTATE_MOVEMENT_ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.LeftRotatePointImpl <em>Left Rotate Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.LeftRotatePointImpl
   * @see robot.dSL.impl.DSLPackageImpl#getLeftRotatePoint()
   * @generated
   */
  int LEFT_ROTATE_POINT = 9;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_ROTATE_POINT__DEGREES = ROTATE_POINTS__DEGREES;

  /**
   * The feature id for the '<em><b>Leftdir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_ROTATE_POINT__LEFTDIR = ROTATE_POINTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Left Rotate Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_ROTATE_POINT_FEATURE_COUNT = ROTATE_POINTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.RightRotatePointImpl <em>Right Rotate Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.RightRotatePointImpl
   * @see robot.dSL.impl.DSLPackageImpl#getRightRotatePoint()
   * @generated
   */
  int RIGHT_ROTATE_POINT = 10;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_ROTATE_POINT__DEGREES = ROTATE_POINTS__DEGREES;

  /**
   * The feature id for the '<em><b>Rightdir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_ROTATE_POINT__RIGHTDIR = ROTATE_POINTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Right Rotate Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_ROTATE_POINT_FEATURE_COUNT = ROTATE_POINTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.MiddleRotatePointImpl <em>Middle Rotate Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.MiddleRotatePointImpl
   * @see robot.dSL.impl.DSLPackageImpl#getMiddleRotatePoint()
   * @generated
   */
  int MIDDLE_ROTATE_POINT = 11;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIDDLE_ROTATE_POINT__DEGREES = ROTATE_POINTS__DEGREES;

  /**
   * The feature id for the '<em><b>Middledir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIDDLE_ROTATE_POINT__MIDDLEDIR = ROTATE_POINTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Middle Rotate Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIDDLE_ROTATE_POINT_FEATURE_COUNT = ROTATE_POINTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.MovementActionImpl <em>Movement Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.MovementActionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getMovementAction()
   * @generated
   */
  int MOVEMENT_ACTION = 12;

  /**
   * The feature id for the '<em><b>Actionenum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVEMENT_ACTION__ACTIONENUM = 0;

  /**
   * The number of structural features of the '<em>Movement Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVEMENT_ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ExpressionBracketImpl <em>Expression Bracket</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ExpressionBracketImpl
   * @see robot.dSL.impl.DSLPackageImpl#getExpressionBracket()
   * @generated
   */
  int EXPRESSION_BRACKET = 13;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BRACKET__EXP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expression Bracket</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BRACKET_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.TouchLiteralImpl <em>Touch Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.TouchLiteralImpl
   * @see robot.dSL.impl.DSLPackageImpl#getTouchLiteral()
   * @generated
   */
  int TOUCH_LITERAL = 14;

  /**
   * The feature id for the '<em><b>Touch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_LITERAL__TOUCH = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Touch Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ColorLiteralImpl <em>Color Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ColorLiteralImpl
   * @see robot.dSL.impl.DSLPackageImpl#getColorLiteral()
   * @generated
   */
  int COLOR_LITERAL = 15;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_LITERAL__COLOR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Color Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.DistanceLiteralImpl <em>Distance Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.DistanceLiteralImpl
   * @see robot.dSL.impl.DSLPackageImpl#getDistanceLiteral()
   * @generated
   */
  int DISTANCE_LITERAL = 16;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE_LITERAL__DISTANCE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Distance Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.EdgeLiteralImpl <em>Edge Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.EdgeLiteralImpl
   * @see robot.dSL.impl.DSLPackageImpl#getEdgeLiteral()
   * @generated
   */
  int EDGE_LITERAL = 17;

  /**
   * The feature id for the '<em><b>Edge</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_LITERAL__EDGE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Edge Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ANDexpressionImpl <em>AN Dexpression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ANDexpressionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getANDexpression()
   * @generated
   */
  int AN_DEXPRESSION = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AN_DEXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AN_DEXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>AN Dexpression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AN_DEXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ORexpressionImpl <em>ORexpression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ORexpressionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getORexpression()
   * @generated
   */
  int OREXPRESSION = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OREXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OREXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>ORexpression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OREXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link robot.dSL.LREnum <em>LR Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.LREnum
   * @see robot.dSL.impl.DSLPackageImpl#getLREnum()
   * @generated
   */
  int LR_ENUM = 20;

  /**
   * The meta object id for the '{@link robot.dSL.FBEnum <em>FB Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.FBEnum
   * @see robot.dSL.impl.DSLPackageImpl#getFBEnum()
   * @generated
   */
  int FB_ENUM = 21;

  /**
   * The meta object id for the '{@link robot.dSL.ActionEnum <em>Action Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.ActionEnum
   * @see robot.dSL.impl.DSLPackageImpl#getActionEnum()
   * @generated
   */
  int ACTION_ENUM = 22;

  /**
   * The meta object id for the '{@link robot.dSL.EdgeEnum <em>Edge Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.EdgeEnum
   * @see robot.dSL.impl.DSLPackageImpl#getEdgeEnum()
   * @generated
   */
  int EDGE_ENUM = 23;

  /**
   * The meta object id for the '{@link robot.dSL.TouchEnum <em>Touch Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.TouchEnum
   * @see robot.dSL.impl.DSLPackageImpl#getTouchEnum()
   * @generated
   */
  int TOUCH_ENUM = 24;

  /**
   * The meta object id for the '{@link robot.dSL.ColorEnum <em>Color Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.ColorEnum
   * @see robot.dSL.impl.DSLPackageImpl#getColorEnum()
   * @generated
   */
  int COLOR_ENUM = 25;


  /**
   * Returns the meta object for class '{@link robot.dSL.MarsRoverExpedition <em>Mars Rover Expedition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mars Rover Expedition</em>'.
   * @see robot.dSL.MarsRoverExpedition
   * @generated
   */
  EClass getMarsRoverExpedition();

  /**
   * Returns the meta object for the containment reference list '{@link robot.dSL.MarsRoverExpedition#getMissionlist <em>Missionlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Missionlist</em>'.
   * @see robot.dSL.MarsRoverExpedition#getMissionlist()
   * @see #getMarsRoverExpedition()
   * @generated
   */
  EReference getMarsRoverExpedition_Missionlist();

  /**
   * Returns the meta object for class '{@link robot.dSL.Mission <em>Mission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission</em>'.
   * @see robot.dSL.Mission
   * @generated
   */
  EClass getMission();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.Mission#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see robot.dSL.Mission#getName()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Name();

  /**
   * Returns the meta object for the containment reference list '{@link robot.dSL.Mission#getBehaviorlist <em>Behaviorlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Behaviorlist</em>'.
   * @see robot.dSL.Mission#getBehaviorlist()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Behaviorlist();

  /**
   * Returns the meta object for class '{@link robot.dSL.Behavior <em>Behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Behavior</em>'.
   * @see robot.dSL.Behavior
   * @generated
   */
  EClass getBehavior();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.Behavior#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see robot.dSL.Behavior#getName()
   * @see #getBehavior()
   * @generated
   */
  EAttribute getBehavior_Name();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.Behavior#getSensorExpression <em>Sensor Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sensor Expression</em>'.
   * @see robot.dSL.Behavior#getSensorExpression()
   * @see #getBehavior()
   * @generated
   */
  EReference getBehavior_SensorExpression();

  /**
   * Returns the meta object for the containment reference list '{@link robot.dSL.Behavior#getActionlist <em>Actionlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actionlist</em>'.
   * @see robot.dSL.Behavior#getActionlist()
   * @see #getBehavior()
   * @generated
   */
  EReference getBehavior_Actionlist();

  /**
   * Returns the meta object for class '{@link robot.dSL.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see robot.dSL.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link robot.dSL.Actions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actions</em>'.
   * @see robot.dSL.Actions
   * @generated
   */
  EClass getActions();

  /**
   * Returns the meta object for class '{@link robot.dSL.LeftMovementAction <em>Left Movement Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left Movement Action</em>'.
   * @see robot.dSL.LeftMovementAction
   * @generated
   */
  EClass getLeftMovementAction();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.LeftMovementAction#getLeftmove <em>Leftmove</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Leftmove</em>'.
   * @see robot.dSL.LeftMovementAction#getLeftmove()
   * @see #getLeftMovementAction()
   * @generated
   */
  EReference getLeftMovementAction_Leftmove();

  /**
   * Returns the meta object for class '{@link robot.dSL.RightMovementAction <em>Right Movement Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right Movement Action</em>'.
   * @see robot.dSL.RightMovementAction
   * @generated
   */
  EClass getRightMovementAction();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.RightMovementAction#getRightmove <em>Rightmove</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rightmove</em>'.
   * @see robot.dSL.RightMovementAction#getRightmove()
   * @see #getRightMovementAction()
   * @generated
   */
  EReference getRightMovementAction_Rightmove();

  /**
   * Returns the meta object for class '{@link robot.dSL.RotateMovementAction <em>Rotate Movement Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate Movement Action</em>'.
   * @see robot.dSL.RotateMovementAction
   * @generated
   */
  EClass getRotateMovementAction();

  /**
   * Returns the meta object for class '{@link robot.dSL.RotatePoints <em>Rotate Points</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate Points</em>'.
   * @see robot.dSL.RotatePoints
   * @generated
   */
  EClass getRotatePoints();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.RotatePoints#getDegrees <em>Degrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degrees</em>'.
   * @see robot.dSL.RotatePoints#getDegrees()
   * @see #getRotatePoints()
   * @generated
   */
  EAttribute getRotatePoints_Degrees();

  /**
   * Returns the meta object for class '{@link robot.dSL.LeftRotatePoint <em>Left Rotate Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left Rotate Point</em>'.
   * @see robot.dSL.LeftRotatePoint
   * @generated
   */
  EClass getLeftRotatePoint();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.LeftRotatePoint#getLeftdir <em>Leftdir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Leftdir</em>'.
   * @see robot.dSL.LeftRotatePoint#getLeftdir()
   * @see #getLeftRotatePoint()
   * @generated
   */
  EAttribute getLeftRotatePoint_Leftdir();

  /**
   * Returns the meta object for class '{@link robot.dSL.RightRotatePoint <em>Right Rotate Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right Rotate Point</em>'.
   * @see robot.dSL.RightRotatePoint
   * @generated
   */
  EClass getRightRotatePoint();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.RightRotatePoint#getRightdir <em>Rightdir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rightdir</em>'.
   * @see robot.dSL.RightRotatePoint#getRightdir()
   * @see #getRightRotatePoint()
   * @generated
   */
  EAttribute getRightRotatePoint_Rightdir();

  /**
   * Returns the meta object for class '{@link robot.dSL.MiddleRotatePoint <em>Middle Rotate Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Middle Rotate Point</em>'.
   * @see robot.dSL.MiddleRotatePoint
   * @generated
   */
  EClass getMiddleRotatePoint();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.MiddleRotatePoint#getMiddledir <em>Middledir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Middledir</em>'.
   * @see robot.dSL.MiddleRotatePoint#getMiddledir()
   * @see #getMiddleRotatePoint()
   * @generated
   */
  EAttribute getMiddleRotatePoint_Middledir();

  /**
   * Returns the meta object for class '{@link robot.dSL.MovementAction <em>Movement Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Movement Action</em>'.
   * @see robot.dSL.MovementAction
   * @generated
   */
  EClass getMovementAction();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.MovementAction#getActionenum <em>Actionenum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Actionenum</em>'.
   * @see robot.dSL.MovementAction#getActionenum()
   * @see #getMovementAction()
   * @generated
   */
  EAttribute getMovementAction_Actionenum();

  /**
   * Returns the meta object for class '{@link robot.dSL.ExpressionBracket <em>Expression Bracket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Bracket</em>'.
   * @see robot.dSL.ExpressionBracket
   * @generated
   */
  EClass getExpressionBracket();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ExpressionBracket#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see robot.dSL.ExpressionBracket#getExp()
   * @see #getExpressionBracket()
   * @generated
   */
  EReference getExpressionBracket_Exp();

  /**
   * Returns the meta object for class '{@link robot.dSL.TouchLiteral <em>Touch Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Touch Literal</em>'.
   * @see robot.dSL.TouchLiteral
   * @generated
   */
  EClass getTouchLiteral();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.TouchLiteral#getTouch <em>Touch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Touch</em>'.
   * @see robot.dSL.TouchLiteral#getTouch()
   * @see #getTouchLiteral()
   * @generated
   */
  EAttribute getTouchLiteral_Touch();

  /**
   * Returns the meta object for class '{@link robot.dSL.ColorLiteral <em>Color Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color Literal</em>'.
   * @see robot.dSL.ColorLiteral
   * @generated
   */
  EClass getColorLiteral();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.ColorLiteral#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see robot.dSL.ColorLiteral#getColor()
   * @see #getColorLiteral()
   * @generated
   */
  EAttribute getColorLiteral_Color();

  /**
   * Returns the meta object for class '{@link robot.dSL.DistanceLiteral <em>Distance Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Distance Literal</em>'.
   * @see robot.dSL.DistanceLiteral
   * @generated
   */
  EClass getDistanceLiteral();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.DistanceLiteral#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see robot.dSL.DistanceLiteral#getDistance()
   * @see #getDistanceLiteral()
   * @generated
   */
  EAttribute getDistanceLiteral_Distance();

  /**
   * Returns the meta object for class '{@link robot.dSL.EdgeLiteral <em>Edge Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Edge Literal</em>'.
   * @see robot.dSL.EdgeLiteral
   * @generated
   */
  EClass getEdgeLiteral();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.EdgeLiteral#getEdge <em>Edge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Edge</em>'.
   * @see robot.dSL.EdgeLiteral#getEdge()
   * @see #getEdgeLiteral()
   * @generated
   */
  EAttribute getEdgeLiteral_Edge();

  /**
   * Returns the meta object for class '{@link robot.dSL.ANDexpression <em>AN Dexpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AN Dexpression</em>'.
   * @see robot.dSL.ANDexpression
   * @generated
   */
  EClass getANDexpression();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ANDexpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see robot.dSL.ANDexpression#getLeft()
   * @see #getANDexpression()
   * @generated
   */
  EReference getANDexpression_Left();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ANDexpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see robot.dSL.ANDexpression#getRight()
   * @see #getANDexpression()
   * @generated
   */
  EReference getANDexpression_Right();

  /**
   * Returns the meta object for class '{@link robot.dSL.ORexpression <em>ORexpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ORexpression</em>'.
   * @see robot.dSL.ORexpression
   * @generated
   */
  EClass getORexpression();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ORexpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see robot.dSL.ORexpression#getLeft()
   * @see #getORexpression()
   * @generated
   */
  EReference getORexpression_Left();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ORexpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see robot.dSL.ORexpression#getRight()
   * @see #getORexpression()
   * @generated
   */
  EReference getORexpression_Right();

  /**
   * Returns the meta object for enum '{@link robot.dSL.LREnum <em>LR Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>LR Enum</em>'.
   * @see robot.dSL.LREnum
   * @generated
   */
  EEnum getLREnum();

  /**
   * Returns the meta object for enum '{@link robot.dSL.FBEnum <em>FB Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>FB Enum</em>'.
   * @see robot.dSL.FBEnum
   * @generated
   */
  EEnum getFBEnum();

  /**
   * Returns the meta object for enum '{@link robot.dSL.ActionEnum <em>Action Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Action Enum</em>'.
   * @see robot.dSL.ActionEnum
   * @generated
   */
  EEnum getActionEnum();

  /**
   * Returns the meta object for enum '{@link robot.dSL.EdgeEnum <em>Edge Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Edge Enum</em>'.
   * @see robot.dSL.EdgeEnum
   * @generated
   */
  EEnum getEdgeEnum();

  /**
   * Returns the meta object for enum '{@link robot.dSL.TouchEnum <em>Touch Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Touch Enum</em>'.
   * @see robot.dSL.TouchEnum
   * @generated
   */
  EEnum getTouchEnum();

  /**
   * Returns the meta object for enum '{@link robot.dSL.ColorEnum <em>Color Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Color Enum</em>'.
   * @see robot.dSL.ColorEnum
   * @generated
   */
  EEnum getColorEnum();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DSLFactory getDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link robot.dSL.impl.MarsRoverExpeditionImpl <em>Mars Rover Expedition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.MarsRoverExpeditionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getMarsRoverExpedition()
     * @generated
     */
    EClass MARS_ROVER_EXPEDITION = eINSTANCE.getMarsRoverExpedition();

    /**
     * The meta object literal for the '<em><b>Missionlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MARS_ROVER_EXPEDITION__MISSIONLIST = eINSTANCE.getMarsRoverExpedition_Missionlist();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.MissionImpl <em>Mission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.MissionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getMission()
     * @generated
     */
    EClass MISSION = eINSTANCE.getMission();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__NAME = eINSTANCE.getMission_Name();

    /**
     * The meta object literal for the '<em><b>Behaviorlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__BEHAVIORLIST = eINSTANCE.getMission_Behaviorlist();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.BehaviorImpl <em>Behavior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.BehaviorImpl
     * @see robot.dSL.impl.DSLPackageImpl#getBehavior()
     * @generated
     */
    EClass BEHAVIOR = eINSTANCE.getBehavior();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEHAVIOR__NAME = eINSTANCE.getBehavior_Name();

    /**
     * The meta object literal for the '<em><b>Sensor Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR__SENSOR_EXPRESSION = eINSTANCE.getBehavior_SensorExpression();

    /**
     * The meta object literal for the '<em><b>Actionlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR__ACTIONLIST = eINSTANCE.getBehavior_Actionlist();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ExpressionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ActionsImpl <em>Actions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ActionsImpl
     * @see robot.dSL.impl.DSLPackageImpl#getActions()
     * @generated
     */
    EClass ACTIONS = eINSTANCE.getActions();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.LeftMovementActionImpl <em>Left Movement Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.LeftMovementActionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getLeftMovementAction()
     * @generated
     */
    EClass LEFT_MOVEMENT_ACTION = eINSTANCE.getLeftMovementAction();

    /**
     * The meta object literal for the '<em><b>Leftmove</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEFT_MOVEMENT_ACTION__LEFTMOVE = eINSTANCE.getLeftMovementAction_Leftmove();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.RightMovementActionImpl <em>Right Movement Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.RightMovementActionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getRightMovementAction()
     * @generated
     */
    EClass RIGHT_MOVEMENT_ACTION = eINSTANCE.getRightMovementAction();

    /**
     * The meta object literal for the '<em><b>Rightmove</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RIGHT_MOVEMENT_ACTION__RIGHTMOVE = eINSTANCE.getRightMovementAction_Rightmove();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.RotateMovementActionImpl <em>Rotate Movement Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.RotateMovementActionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getRotateMovementAction()
     * @generated
     */
    EClass ROTATE_MOVEMENT_ACTION = eINSTANCE.getRotateMovementAction();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.RotatePointsImpl <em>Rotate Points</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.RotatePointsImpl
     * @see robot.dSL.impl.DSLPackageImpl#getRotatePoints()
     * @generated
     */
    EClass ROTATE_POINTS = eINSTANCE.getRotatePoints();

    /**
     * The meta object literal for the '<em><b>Degrees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_POINTS__DEGREES = eINSTANCE.getRotatePoints_Degrees();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.LeftRotatePointImpl <em>Left Rotate Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.LeftRotatePointImpl
     * @see robot.dSL.impl.DSLPackageImpl#getLeftRotatePoint()
     * @generated
     */
    EClass LEFT_ROTATE_POINT = eINSTANCE.getLeftRotatePoint();

    /**
     * The meta object literal for the '<em><b>Leftdir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEFT_ROTATE_POINT__LEFTDIR = eINSTANCE.getLeftRotatePoint_Leftdir();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.RightRotatePointImpl <em>Right Rotate Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.RightRotatePointImpl
     * @see robot.dSL.impl.DSLPackageImpl#getRightRotatePoint()
     * @generated
     */
    EClass RIGHT_ROTATE_POINT = eINSTANCE.getRightRotatePoint();

    /**
     * The meta object literal for the '<em><b>Rightdir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIGHT_ROTATE_POINT__RIGHTDIR = eINSTANCE.getRightRotatePoint_Rightdir();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.MiddleRotatePointImpl <em>Middle Rotate Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.MiddleRotatePointImpl
     * @see robot.dSL.impl.DSLPackageImpl#getMiddleRotatePoint()
     * @generated
     */
    EClass MIDDLE_ROTATE_POINT = eINSTANCE.getMiddleRotatePoint();

    /**
     * The meta object literal for the '<em><b>Middledir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MIDDLE_ROTATE_POINT__MIDDLEDIR = eINSTANCE.getMiddleRotatePoint_Middledir();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.MovementActionImpl <em>Movement Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.MovementActionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getMovementAction()
     * @generated
     */
    EClass MOVEMENT_ACTION = eINSTANCE.getMovementAction();

    /**
     * The meta object literal for the '<em><b>Actionenum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVEMENT_ACTION__ACTIONENUM = eINSTANCE.getMovementAction_Actionenum();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ExpressionBracketImpl <em>Expression Bracket</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ExpressionBracketImpl
     * @see robot.dSL.impl.DSLPackageImpl#getExpressionBracket()
     * @generated
     */
    EClass EXPRESSION_BRACKET = eINSTANCE.getExpressionBracket();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_BRACKET__EXP = eINSTANCE.getExpressionBracket_Exp();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.TouchLiteralImpl <em>Touch Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.TouchLiteralImpl
     * @see robot.dSL.impl.DSLPackageImpl#getTouchLiteral()
     * @generated
     */
    EClass TOUCH_LITERAL = eINSTANCE.getTouchLiteral();

    /**
     * The meta object literal for the '<em><b>Touch</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOUCH_LITERAL__TOUCH = eINSTANCE.getTouchLiteral_Touch();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ColorLiteralImpl <em>Color Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ColorLiteralImpl
     * @see robot.dSL.impl.DSLPackageImpl#getColorLiteral()
     * @generated
     */
    EClass COLOR_LITERAL = eINSTANCE.getColorLiteral();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_LITERAL__COLOR = eINSTANCE.getColorLiteral_Color();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.DistanceLiteralImpl <em>Distance Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.DistanceLiteralImpl
     * @see robot.dSL.impl.DSLPackageImpl#getDistanceLiteral()
     * @generated
     */
    EClass DISTANCE_LITERAL = eINSTANCE.getDistanceLiteral();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISTANCE_LITERAL__DISTANCE = eINSTANCE.getDistanceLiteral_Distance();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.EdgeLiteralImpl <em>Edge Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.EdgeLiteralImpl
     * @see robot.dSL.impl.DSLPackageImpl#getEdgeLiteral()
     * @generated
     */
    EClass EDGE_LITERAL = eINSTANCE.getEdgeLiteral();

    /**
     * The meta object literal for the '<em><b>Edge</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDGE_LITERAL__EDGE = eINSTANCE.getEdgeLiteral_Edge();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ANDexpressionImpl <em>AN Dexpression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ANDexpressionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getANDexpression()
     * @generated
     */
    EClass AN_DEXPRESSION = eINSTANCE.getANDexpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AN_DEXPRESSION__LEFT = eINSTANCE.getANDexpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AN_DEXPRESSION__RIGHT = eINSTANCE.getANDexpression_Right();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ORexpressionImpl <em>ORexpression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ORexpressionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getORexpression()
     * @generated
     */
    EClass OREXPRESSION = eINSTANCE.getORexpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OREXPRESSION__LEFT = eINSTANCE.getORexpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OREXPRESSION__RIGHT = eINSTANCE.getORexpression_Right();

    /**
     * The meta object literal for the '{@link robot.dSL.LREnum <em>LR Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.LREnum
     * @see robot.dSL.impl.DSLPackageImpl#getLREnum()
     * @generated
     */
    EEnum LR_ENUM = eINSTANCE.getLREnum();

    /**
     * The meta object literal for the '{@link robot.dSL.FBEnum <em>FB Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.FBEnum
     * @see robot.dSL.impl.DSLPackageImpl#getFBEnum()
     * @generated
     */
    EEnum FB_ENUM = eINSTANCE.getFBEnum();

    /**
     * The meta object literal for the '{@link robot.dSL.ActionEnum <em>Action Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.ActionEnum
     * @see robot.dSL.impl.DSLPackageImpl#getActionEnum()
     * @generated
     */
    EEnum ACTION_ENUM = eINSTANCE.getActionEnum();

    /**
     * The meta object literal for the '{@link robot.dSL.EdgeEnum <em>Edge Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.EdgeEnum
     * @see robot.dSL.impl.DSLPackageImpl#getEdgeEnum()
     * @generated
     */
    EEnum EDGE_ENUM = eINSTANCE.getEdgeEnum();

    /**
     * The meta object literal for the '{@link robot.dSL.TouchEnum <em>Touch Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.TouchEnum
     * @see robot.dSL.impl.DSLPackageImpl#getTouchEnum()
     * @generated
     */
    EEnum TOUCH_ENUM = eINSTANCE.getTouchEnum();

    /**
     * The meta object literal for the '{@link robot.dSL.ColorEnum <em>Color Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.ColorEnum
     * @see robot.dSL.impl.DSLPackageImpl#getColorEnum()
     * @generated
     */
    EEnum COLOR_ENUM = eINSTANCE.getColorEnum();

  }

} //DSLPackage
