/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Edge Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.EdgeLiteral#getEdge <em>Edge</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getEdgeLiteral()
 * @model
 * @generated
 */
public interface EdgeLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Edge</b></em>' attribute.
   * The literals are from the enumeration {@link robot.dSL.EdgeEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Edge</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edge</em>' attribute.
   * @see robot.dSL.EdgeEnum
   * @see #setEdge(EdgeEnum)
   * @see robot.dSL.DSLPackage#getEdgeLiteral_Edge()
   * @model
   * @generated
   */
  EdgeEnum getEdge();

  /**
   * Sets the value of the '{@link robot.dSL.EdgeLiteral#getEdge <em>Edge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Edge</em>' attribute.
   * @see robot.dSL.EdgeEnum
   * @see #getEdge()
   * @generated
   */
  void setEdge(EdgeEnum value);

} // EdgeLiteral
