/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.EndCondition#getEndwhenlist <em>Endwhenlist</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getEndCondition()
 * @model
 * @generated
 */
public interface EndCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Endwhenlist</b></em>' containment reference list.
   * The list contents are of type {@link robot.dSL.EndWhen}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Endwhenlist</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Endwhenlist</em>' containment reference list.
   * @see robot.dSL.DSLPackage#getEndCondition_Endwhenlist()
   * @model containment="true"
   * @generated
   */
  EList<EndWhen> getEndwhenlist();

} // EndCondition
