/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left Movement Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.LeftMovementAction#getLeftmove <em>Leftmove</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getLeftMovementAction()
 * @model
 * @generated
 */
public interface LeftMovementAction extends Actions
{
  /**
   * Returns the value of the '<em><b>Leftmove</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Leftmove</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Leftmove</em>' containment reference.
   * @see #setLeftmove(MovementAction)
   * @see robot.dSL.DSLPackage#getLeftMovementAction_Leftmove()
   * @model containment="true"
   * @generated
   */
  MovementAction getLeftmove();

  /**
   * Sets the value of the '{@link robot.dSL.LeftMovementAction#getLeftmove <em>Leftmove</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Leftmove</em>' containment reference.
   * @see #getLeftmove()
   * @generated
   */
  void setLeftmove(MovementAction value);

} // LeftMovementAction
