/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mars Rover Expedition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.MarsRoverExpedition#getMissionlist <em>Missionlist</em>}</li>
 *   <li>{@link robot.dSL.MarsRoverExpedition#getTasklist <em>Tasklist</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getMarsRoverExpedition()
 * @model
 * @generated
 */
public interface MarsRoverExpedition extends EObject
{
  /**
   * Returns the value of the '<em><b>Missionlist</b></em>' containment reference list.
   * The list contents are of type {@link robot.dSL.Mission}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Missionlist</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Missionlist</em>' containment reference list.
   * @see robot.dSL.DSLPackage#getMarsRoverExpedition_Missionlist()
   * @model containment="true"
   * @generated
   */
  EList<Mission> getMissionlist();

  /**
   * Returns the value of the '<em><b>Tasklist</b></em>' containment reference list.
   * The list contents are of type {@link robot.dSL.Behavior}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tasklist</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasklist</em>' containment reference list.
   * @see robot.dSL.DSLPackage#getMarsRoverExpedition_Tasklist()
   * @model containment="true"
   * @generated
   */
  EList<Behavior> getTasklist();

} // MarsRoverExpedition
