/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Movement Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.MovementAction#getActionenum <em>Actionenum</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getMovementAction()
 * @model
 * @generated
 */
public interface MovementAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Actionenum</b></em>' attribute.
   * The literals are from the enumeration {@link robot.dSL.ActionEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actionenum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actionenum</em>' attribute.
   * @see robot.dSL.ActionEnum
   * @see #setActionenum(ActionEnum)
   * @see robot.dSL.DSLPackage#getMovementAction_Actionenum()
   * @model
   * @generated
   */
  ActionEnum getActionenum();

  /**
   * Sets the value of the '{@link robot.dSL.MovementAction#getActionenum <em>Actionenum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actionenum</em>' attribute.
   * @see robot.dSL.ActionEnum
   * @see #getActionenum()
   * @generated
   */
  void setActionenum(ActionEnum value);

} // MovementAction
