/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.MoveAction#getDir <em>Dir</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getMoveAction()
 * @model
 * @generated
 */
public interface MoveAction extends Actions
{
  /**
   * Returns the value of the '<em><b>Dir</b></em>' attribute.
   * The literals are from the enumeration {@link robot.dSL.FBEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dir</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dir</em>' attribute.
   * @see robot.dSL.FBEnum
   * @see #setDir(FBEnum)
   * @see robot.dSL.DSLPackage#getMoveAction_Dir()
   * @model
   * @generated
   */
  FBEnum getDir();

  /**
   * Sets the value of the '{@link robot.dSL.MoveAction#getDir <em>Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dir</em>' attribute.
   * @see robot.dSL.FBEnum
   * @see #getDir()
   * @generated
   */
  void setDir(FBEnum value);

} // MoveAction
