/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right Rotate Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.RightRotatePoint#getRightdir <em>Rightdir</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getRightRotatePoint()
 * @model
 * @generated
 */
public interface RightRotatePoint extends RotatePoints
{
  /**
   * Returns the value of the '<em><b>Rightdir</b></em>' attribute.
   * The literals are from the enumeration {@link robot.dSL.FBEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rightdir</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rightdir</em>' attribute.
   * @see robot.dSL.FBEnum
   * @see #setRightdir(FBEnum)
   * @see robot.dSL.DSLPackage#getRightRotatePoint_Rightdir()
   * @model
   * @generated
   */
  FBEnum getRightdir();

  /**
   * Sets the value of the '{@link robot.dSL.RightRotatePoint#getRightdir <em>Rightdir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rightdir</em>' attribute.
   * @see robot.dSL.FBEnum
   * @see #getRightdir()
   * @generated
   */
  void setRightdir(FBEnum value);

} // RightRotatePoint
