/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right Movement Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.RightMovementAction#getRightmove <em>Rightmove</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getRightMovementAction()
 * @model
 * @generated
 */
public interface RightMovementAction extends Actions
{
  /**
   * Returns the value of the '<em><b>Rightmove</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rightmove</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rightmove</em>' containment reference.
   * @see #setRightmove(MovementAction)
   * @see robot.dSL.DSLPackage#getRightMovementAction_Rightmove()
   * @model containment="true"
   * @generated
   */
  MovementAction getRightmove();

  /**
   * Sets the value of the '{@link robot.dSL.RightMovementAction#getRightmove <em>Rightmove</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rightmove</em>' containment reference.
   * @see #getRightmove()
   * @generated
   */
  void setRightmove(MovementAction value);

} // RightMovementAction
