/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotate Points</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.RotatePoints#getDegrees <em>Degrees</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getRotatePoints()
 * @model
 * @generated
 */
public interface RotatePoints extends RotateMovementAction
{
  /**
   * Returns the value of the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Degrees</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degrees</em>' attribute.
   * @see #setDegrees(int)
   * @see robot.dSL.DSLPackage#getRotatePoints_Degrees()
   * @model
   * @generated
   */
  int getDegrees();

  /**
   * Sets the value of the '{@link robot.dSL.RotatePoints#getDegrees <em>Degrees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Degrees</em>' attribute.
   * @see #getDegrees()
   * @generated
   */
  void setDegrees(int value);

} // RotatePoints
