/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotate Movement Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see robot.dSL.DSLPackage#getRotateMovementAction()
 * @model
 * @generated
 */
public interface RotateMovementAction extends Actions
{
} // RotateMovementAction
