/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Touch Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.TouchLiteral#getTouch <em>Touch</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getTouchLiteral()
 * @model
 * @generated
 */
public interface TouchLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Touch</b></em>' attribute.
   * The literals are from the enumeration {@link robot.dSL.TouchEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Touch</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Touch</em>' attribute.
   * @see robot.dSL.TouchEnum
   * @see #setTouch(TouchEnum)
   * @see robot.dSL.DSLPackage#getTouchLiteral_Touch()
   * @model
   * @generated
   */
  TouchEnum getTouch();

  /**
   * Sets the value of the '{@link robot.dSL.TouchLiteral#getTouch <em>Touch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Touch</em>' attribute.
   * @see robot.dSL.TouchEnum
   * @see #getTouch()
   * @generated
   */
  void setTouch(TouchEnum value);

} // TouchLiteral
