/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>True Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.TrueLiteral#getT <em>T</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getTrueLiteral()
 * @model
 * @generated
 */
public interface TrueLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>T</b></em>' attribute.
   * The literals are from the enumeration {@link robot.dSL.Tenum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>T</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' attribute.
   * @see robot.dSL.Tenum
   * @see #setT(Tenum)
   * @see robot.dSL.DSLPackage#getTrueLiteral_T()
   * @model
   * @generated
   */
  Tenum getT();

  /**
   * Sets the value of the '{@link robot.dSL.TrueLiteral#getT <em>T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' attribute.
   * @see robot.dSL.Tenum
   * @see #getT()
   * @generated
   */
  void setT(Tenum value);

} // TrueLiteral
