/**
 * generated by Xtext 2.10.0
 */
package robot.dSL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import robot.dSL.DSLPackage;
import robot.dSL.FBEnum;
import robot.dSL.LeftRotatePoint;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Left Rotate Point</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.impl.LeftRotatePointImpl#getLeftdir <em>Leftdir</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LeftRotatePointImpl extends RotatePointsImpl implements LeftRotatePoint
{
  /**
   * The default value of the '{@link #getLeftdir() <em>Leftdir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftdir()
   * @generated
   * @ordered
   */
  protected static final FBEnum LEFTDIR_EDEFAULT = FBEnum.FORWARD;

  /**
   * The cached value of the '{@link #getLeftdir() <em>Leftdir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftdir()
   * @generated
   * @ordered
   */
  protected FBEnum leftdir = LEFTDIR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LeftRotatePointImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DSLPackage.Literals.LEFT_ROTATE_POINT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FBEnum getLeftdir()
  {
    return leftdir;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLeftdir(FBEnum newLeftdir)
  {
    FBEnum oldLeftdir = leftdir;
    leftdir = newLeftdir == null ? LEFTDIR_EDEFAULT : newLeftdir;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLPackage.LEFT_ROTATE_POINT__LEFTDIR, oldLeftdir, leftdir));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DSLPackage.LEFT_ROTATE_POINT__LEFTDIR:
        return getLeftdir();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DSLPackage.LEFT_ROTATE_POINT__LEFTDIR:
        setLeftdir((FBEnum)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DSLPackage.LEFT_ROTATE_POINT__LEFTDIR:
        setLeftdir(LEFTDIR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DSLPackage.LEFT_ROTATE_POINT__LEFTDIR:
        return leftdir != LEFTDIR_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (leftdir: ");
    result.append(leftdir);
    result.append(')');
    return result.toString();
  }

} //LeftRotatePointImpl
