/*
 * generated by Xtext 2.10.0
 */
package robot.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import robot.ui.internal.RobotActivator;

public class DSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotActivator.getInstance().getInjector("robot.DSL");
	}

}
