/*
 * generated by Xtext 2.10.0
 */
package robot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDSLScopeProvider extends DelegatingScopeProvider {
}
