/**
 * generated by Xtext 2.10.0
 */
package robot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import robot.ui.AbstractDSLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DSLUiModule extends AbstractDSLUiModule {
  public DSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
