/**
 * generated by Xtext 2.10.0
 */
package robot.ui.contentassist;

import robot.ui.contentassist.AbstractDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DSLProposalProvider extends AbstractDSLProposalProvider {
}
