/*
 * generated by Xtext 2.10.0
 */
package robot.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import robot.dSL.MarsRoverExpedition

@RunWith(XtextRunner)
@InjectWith(DSLInjectorProvider)
class DSLParsingTest{

	@Inject
	ParseHelper<MarsRoverExpedition> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
