/**
 * generated by Xtext 2.10.0
 */
package robot;

import robot.AbstractDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
